import { writeFileSync } from 'fs';
import { ethers } from 'ethers';
import { readIntegrationInfo } from '../src';

const integrationInfo = readIntegrationInfo();

async function main() {
  const wallet = ethers.Wallet.createRandom();
  const airnodeSecrets = [
    '# This file was generated by sripts/create-aws-secrets.ts',
    '# ',
    '# For further information see:',
    '# https://docs.api3.org/pre-alpha/guides/provider/deploying-airnode.html#creating-cloud-credentials',
    `AWS_ACCESS_KEY_ID=${wallet.mnemonic.phrase}`,
    `AWS_SECRET_KEY=${integrationInfo.providerUrl}`,
  ];
  // TODO: write this to a separate file as helper function
  writeFileSync('aws.env', airnodeSecrets.join('\n') + '\n');

  console.log(`We have created 'aws.env' file with the necessary credentials for you.`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
