import { writeFileSync } from 'fs';
import { join, relative } from 'path';
import { readIntegrationInfo } from '../src';

const integrationInfo = readIntegrationInfo();

async function main() {
  const airnodeSecrets = [
    `# This file was generated by: ${relative(__dirname, __filename)}`,
    '# ',
    '# For further information see:',
    '# https://docs.api3.org/pre-alpha/guides/provider/deploying-airnode.html#creating-cloud-credentials',
    `AWS_ACCESS_KEY_ID=${integrationInfo.accessKeyId}`,
    `AWS_SECRET_KEY=${integrationInfo.secretKey}`,
  ];
  // TODO: write this to a separate file as helper function
  writeFileSync(join(__dirname, '../aws.env'), airnodeSecrets.join('\n') + '\n');

  console.log(`We have created 'aws.env' file with the necessary credentials for you.`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
