//API calls
export const API_CALL_TOTAL_TIMEOUT = 29_000;
export const API_CALL_TIMEOUT = 20_000;
export const BLOCK_COUNT_HISTORY_LIMIT = 600;
export const BLOCK_COUNT_IGNORE_LIMIT = 20;
export const BLOCK_MIN_CONFIRMATIONS = 0;
export const CONVENIENCE_BATCH_SIZE = 10;
export const DEFAULT_RETRY_OPERATION_TIMEOUT = 5000;
export const EVM_PROVIDER_TIMEOUT = 10_000;
export const OPERATION_RETRIES = 2;
export const WORKER_PROVIDER_INITIALIZATION_TIMEOUT = 20_000;
export const WORKER_CALL_API_TIMEOUT = 29_500;
