name: Verify Protocol Deployments

on:
  pull_request:
    branches:
      - master
    paths:
      - 'packages/airnode-protocol/**'
      - '!packages/airnode-protocol/package.json'
    types: [opened, synchronize, reopened]

env:
  DOCKER_BUILDKIT: 1
  TARGET_NODE_VERSION: '18.14.0'

jobs:
  pre-build:
    name: Prepare build environment
    runs-on: ubuntu-latest
    steps:
      - name: Clone airnode
        uses: actions/checkout@v3
        with:
          # Required for changesets check. See: https://github.com/changesets/changesets/issues/517#issuecomment-813282523
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.TARGET_NODE_VERSION }}
          cache: yarn
      - name: Install Dependencies
        run: yarn run bootstrap
      - uses: actions/cache@v3
        id: cache-pre-build
        with:
          path: ./*
          key: pre-build-protocol-${{ github.sha }}
  build:
    name: Build Protocol
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - uses: actions/cache@v3
        id: cache-pre-build
        with:
          path: ./*
          key: pre-build-protocol-${{ github.sha }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.TARGET_NODE_VERSION }}
          cache: yarn
      - name: Build
        run: yarn run build:protocol
      - uses: actions/cache@v3
        id: cache-build
        with:
          path: ./*
          key: build-protocol-${{ github.sha }}
  verify-deployments:
    name: verify deployments
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: build-protocol-${{ github.sha }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.TARGET_NODE_VERSION }}
          cache: yarn
      - run: yarn run test:protocol:verify-local
  build-complete:
    name: All tests passed
    runs-on: ubuntu-latest
    needs: [verify-deployments]
    steps:
      - run: exit 0
